### ISSUE TITLE
Persistant URL for a shared DB

### ISSUE THREAD

**Issue by nicholaskillin** [heisch/gloomhaven-item-db#4]
Hey, this is GREAT and would help our team out so much while social distancing. One thing that I discovered though is that anytime someone makes a change, the URL that they need to use to access the updated database changes. 

This makes it very hard for us to all stay on the same page. From what I can tell this means that only 1 person could make changes at a time, and every time they do they would have to share the new link with the entire party once they are done making changes again so that we always have the most recently URL.

Is there any chance the app would be able to generate a unique URL when someone visits the page for the first time, then if someone accesses a saved URL it could just update that existing URL instead of making a new one every time something changes? This would make managing the party market MUCH easier for us.

Thanks!

**Comment by heisch** [comment]
Currently that's not possible since there is no server-side save.
All your settings are encoded in the the generated URL that's why it changes every time you change something.
I'm not planning on creating new features for this tool any time soon (haven't played Gloomhaven in a while either) so I'll close this request for now
